trigger:
  batch: true

variables:
  # Change the following along with adding new TEST_START_INDEX.
  TEST_COUNT: 18
  
jobs:
# Mac and Linux use the same template with different matrixes
- template: buildscripts/azure/azure-linux-macos.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    matrix:
      py37_np116_tbb:
        PYTHON: '3.7'
        NUMPY: '1.16'
        CONDA_ENV: travisci
        TEST_THREADING: 'tbb'
        TEST_START_INDEX: 2
- template: buildscripts/azure/azure-linux-aarch64.yml
  parameters:
    pool: AArch64_agent
    #arch: arm64
    #qemu_arch: aarch64
    vmImage: 'ubuntu-latest'
    matrix:
      AArch64_agent_01:
        PYTHON: '3.7'
        NUMPY: '1.16'
        CONDA_ENV: travisci
        TEST_THREADING: 'tbb'
        TEST_START_INDEX: 2

