trigger:
  batch: true

variables:
  # Change the following along with adding new TEST_START_INDEX.
  TEST_COUNT: 18

jobs:
# Mac and Linux use the same template with different matrixes
- template: buildscripts/azure/azure-linux-macos.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    matrix:
      py38_np118:
        PYTHON: '3.8'
        NUMPY: '1.18'
        CONDA_ENV: travisci
        TEST_START_INDEX: 15

#- template: buildscripts/azure/azure-linux-aarch64.yml
#  parameters:
#    pool: AArch64_agent
#    vmImage: 'multiarch/ubuntu-core:arm64-bionic'
#    matrix:
#      AArch64_agent_01:
#        PYTHON: '3.8'
#        NUMPY: '1.17'
#        CONDA_ENV: travisci
#        TEST_START_INDEX: 0
#
#- template: buildscripts/azure/azure-windows.yml
#  parameters:
#    name: Windows
#    vmImage: vs2017-win2016
#
