parameters:
  name: ''
  vmImage: ''
  pool: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - script: docker run --rm --privileged hypriot/qemu-register
      displayName: 'Regietering qemu'
    - script: |
        export DOCKER_IMAGE=condaforge/linux-anvil-aarch64
        bash buildscripts/incremental/run_docker_build.sh
      displayName: 'Running AArch64 build'
