parameters:
  name: ''
  vmImage: ''
  pool: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - script: |
        sudo apt-get install qemu-user
        sudo apt-get install qemu-user-static
        sudo apt-get install qemu-system
        sudo apt-get install qemu-system-arm
        sudo apt-get install qemu
      displayName: 'Installing qemu libraries'
    - script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      displayName: 'Regietering qemu'
    - script: |
        #export DOCKER_IMAGE=condaforge/linux-anvil-aarch64
        export DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
        bash buildscripts/incremental/run_docker_build.sh
      displayName: 'Running AArch64 build'
