parameters:
  name: ''
  vmImage: ''
  pool: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - script: docker run --rm --privileged hypriot/qemu-register
    - script: docker run --rm quay.io/pypa/manylinux2014_aarch64 bash
    - script: |
        #docker run --rm -it -v ./:/home/numba:rw,z quay.io/pypa/manylinux2014_aarch64 bash
        yum update
        #cd /home/numba
        #python setup.py install
      displayName: 'Before Install'

    - script: |
        export PATH=$HOME/miniconda/bin:$PATH
        buildscripts/incremental/build.sh
      displayName: 'Build'

    - script: |
        export PATH=$HOME/miniconda/bin:$PATH
        conda install -y flake8
        flake8 numba
      displayName: 'Flake8'
      condition: eq(variables['RUN_FLAKE8'], 'yes')

    - script: |
        export PATH=$HOME/miniconda/bin:$PATH
        buildscripts/incremental/test.sh
      displayName: 'Test'
