parameters:
  name: ''
  vmImage: ''
  pool: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    name: ${{ parameters.pool }}
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - script: docker run --rm --privileged hypriot/qemu-register
    - script: |
        echo "Installing Miniconda"
        #buildscripts/incremental/install_miniconda.sh
        export PATH=$HOME/miniconda/bin:$PATH
        echo "Setting up Conda environment"
        buildscripts/incremental/setup_conda_environment.sh
      displayName: 'Before Install'

    - script: |
        export PATH=$HOME/miniconda/bin:$PATH
        buildscripts/incremental/build.sh
      displayName: 'Build'

    - script: |
        export PATH=$HOME/miniconda/bin:$PATH
        conda install -y flake8
        flake8 numba
      displayName: 'Flake8'
      condition: eq(variables['RUN_FLAKE8'], 'yes')

    - script: |
        export PATH=$HOME/miniconda/bin:$PATH
        buildscripts/incremental/test.sh
      displayName: 'Test'
